name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: export -p
      run:  export -p

    - name: brew install gnu-sed
      if:   matrix.os == 'macos-11.0'
      run:  brew install gnu-sed

    - name: brew install 
      run:  brew install automake autoconf libtool pkg-config cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - name: ipkg version
      run:  ipkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ipkg/formula
      run: |
        install -d $HOME/.ipkg/formula
        mv *.sh    $HOME/.ipkg/formula

    - name: ipkg install boost
      run:  ipkg install boost
