name: ci1 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        pkg: [axel,bc,bcrypt,berkeley-db,bison,ccache,check,cjson,cpio,cpu_features,dash,diffutils,dmalloc,double-conversion,faac,faad2,fdk-aac,ffmpeg,file,findutils,flex,fmt,fribidi,gawk,glog,gnu-coreutils,gnu-sed,gnu-tar,gnu-which,gnupg,google-benchmark,google-test,gperf,graphite2,grep,gzip,hwloc,ideviceinstaller,isl,json-glib,jsoncpp,libarchive,libatomic_ops,libb2,libbcrypt]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run:  brew install gnu-sed

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ipkg/formula
      run: |
        install -d $HOME/.ipkg/formula
        mv *.sh    $HOME/.ipkg/formula

    - run: ipkg install ${{ matrix.pkg }}
