name: ci1 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        pkg: [bash,bc,bcrypt,bind,binutils,bison,ccache,check,cjson,cmake,cpio,cpu_features,crosstool-ng,dash,diffutils,dmalloc,faac,faad2,fdk-aac,ffmpeg,file,findutils,fish,flex,folly,gawk,git,gnu-coreutils,gnu-sed,gnu-tar,gnu-which,gnupg,gnutls,google-benchmark,google-test,gperf,graphite2,grep,gzip,htop,hwloc,id3lib,ideviceinstaller,imlib2,jemalloc,json-glib,jsoncpp,krb5,less,libao]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run:  brew install gnu-sed automake autoconf libtool pkg-config cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ipkg/formula
      run: |
        install -d $HOME/.ipkg/formula
        mv *.sh    $HOME/.ipkg/formula

    - run: ipkg install ${{ matrix.pkg }}
