name: ci1 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]
        pkg: [axel,bc,bcrypt,berkeley-db,bind,bison,ccache,check,cjson,cmake,cpio,cpu_features,dash,diffutils,dmalloc,double-conversion,faac,faad2,fdk-aac,ffmpeg,file,findutils,fish,flex,fmt,fribidi,gawk,gdbm,glog,gnu-coreutils,gnu-sed,gnu-tar,gnu-which,gnupg,gnutls,google-benchmark,gperf,graphite2,grep,gzip,hexdump,hwloc,ideviceinstaller,isl,jq,json-glib,jsoncpp,libarchive,libatomic_ops,libb2]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install xcpkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/bin/xcpkg
        chmod u+x xcpkg
        mv xcpkg $(brew --prefix)/bin

    - run:  xcpkg env

    - run:  xcpkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.xcpkg/repos.d/offical
    - run: mv *       ~/.xcpkg/repos.d/offical

    - run: xcpkg install ${{ matrix.pkg }} --tree
