name: ci2 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        pkg: [libass,libatomic_ops,libb2,libbcrypt,libcddb,libcdio,libcroco,libexif,libgit2,libimagequant,libisoburn,libmetalink,libpipeline,libpsl,libsamplerate,libsigsegv,libsmi,libtool,libxslt,links,lodepng,lynx,lzip,m4,make,mbedtls,mpg123,mpir,nasm,nginx,ngtcp2,nspr,ntbtls,openlibm,openmpi,openssl-fips,packcc,patch,pixman,pkg-config,pkgconf,pngquant,protobuf,qrencode,re2,rhash,rsync,swig,tcpdump,texinfo]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run:  brew install gnu-sed

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ipkg/formula
      run: |
        install -d $HOME/.ipkg/formula
        mv *.sh    $HOME/.ipkg/formula

    - run: ipkg install ${{ matrix.pkg }}
