name: ci2 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]
        pkg: [libbcrypt,libcaca,libcddb,libcdio,libcroco,libexif,libgit2,libimagequant,libisoburn,libmetalink,libmpc,libphonenumber,libpipeline,libpsl,libsamplerate,libsmi,libsodium,libtool,libtorrent-rasterbar,libxslt,libyuv,links,lmdb,lodepng,lynx,lzip,m4,make,mediainfo,mpg123,mpir,nanomsg,nasm,nginx,ngtcp2,nng,nspr,ntbtls,openblas,openlibm,openmpi,packcc,patch,pixman,pkg-config,pkgconf,pngquant,qrencode,quickjs,re2]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install xcpkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/bin/xcpkg
        chmod u+x xcpkg
        mv xcpkg $(brew --prefix)/bin

    - run:  xcpkg env

    - run:  xcpkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.xcpkg/repos.d/offical
    - run: mv *       ~/.xcpkg/repos.d/offical

    - run: xcpkg install ${{ matrix.pkg }} --tree
