name: ci3 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        pkg: [rtorrent,snappy,swig,tcpdump,texinfo,tree,universal-ctags,unrar,unzip,utf8proc,vala,xorriso,xvid,yasm]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run:  brew install gnu-sed

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ipkg/formula
      run: |
        install -d $HOME/.ipkg/formula
        mv *.sh    $HOME/.ipkg/formula

    - run: ipkg install ${{ matrix.pkg }}
