name: ci3 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]
        pkg: [rhash,rsync,rtmpdump,rtorrent,snappy,swig,tcpdump,texinfo,tree,unbound,universal-ctags,unrar,unzip,utf8proc,vala,wolfssl,xorriso,xvid,yasm,zlib-ng,libidn]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg env

    - run:  ipkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.ipkg/repos.d/offical
    - run: mv *       ~/.ipkg/repos.d/offical

    - run: ipkg install ${{ matrix.pkg }}
