name: ci0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        pkg: [bind,fish,gnutls,libtorrent-rasterbar]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - name: install ipkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ipkg/master/bin/ipkg
        chmod u+x ipkg
        mv ipkg $(brew --prefix)/bin

    - run:  ipkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.ndk-pkg/repos.d/offical
    - run: mv *       ~/.ndk-pkg/repos.d/offical

    - run: ipkg install ${{ matrix.pkg }} --rule=thread-local-storage
